<a href="https://colab.research.google.com/github/cantaruttim/Teste_Hipotese/blob/main/TesteHipotese.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
from scipy.stats import norm

In [ ]:
dados_originais = np.array([126. , 129.5, 133. , 133. , 136.5, 136.5, 140. , 140. , 140. ,
                            140. , 143.5, 143.5, 143.5, 143.5, 143.5, 143.5, 147. , 147. ,
                            147. , 147. , 147. , 147. , 147. , 150.5, 150.5, 150.5, 150.5,
                            150.5, 150.5, 150.5, 150.5, 154. , 154. , 154. , 154. , 154. ,
                            154. , 154. , 154. , 154. , 157.5, 157.5, 157.5, 157.5, 157.5,
                            157.5, 157.5, 157.5, 157.5, 157.5, 161. , 161. , 161. , 161. ,
                            161. , 161. , 161. , 161. , 161. , 161. , 164.5, 164.5, 164.5,
                            164.5, 164.5, 164.5, 164.5, 164.5, 164.5, 168. , 168. , 168. ,
                            168. , 168. , 168. , 168. , 168. , 171.5, 171.5, 171.5, 171.5,
                            171.5, 171.5, 171.5, 175. , 175. , 175. , 175. , 175. , 175. ,
                            178.5, 178.5, 178.5, 178.5, 182. , 182. , 185.5, 185.5, 189., 192.5])

In [ ]:
# H0 (Hipótese Nula ==> Média = 159.25)
H0_media = np.mean(dados_originais)
H0_media

159.25

In [ ]:
H0_desvio_padrao = np.std(dados_originais)
H0_desvio_padrao

13.65

In [ ]:
dados_novos = dados_originais * 1.03
dados_novos

array([129.78 , 133.385, 136.99 , 136.99 , 140.595, 140.595, 144.2  ,
       144.2  , 144.2  , 144.2  , 147.805, 147.805, 147.805, 147.805,
       147.805, 147.805, 151.41 , 151.41 , 151.41 , 151.41 , 151.41 ,
       151.41 , 151.41 , 155.015, 155.015, 155.015, 155.015, 155.015,
       155.015, 155.015, 155.015, 158.62 , 158.62 , 158.62 , 158.62 ,
       158.62 , 158.62 , 158.62 , 158.62 , 158.62 , 162.225, 162.225,
       162.225, 162.225, 162.225, 162.225, 162.225, 162.225, 162.225,
       162.225, 165.83 , 165.83 , 165.83 , 165.83 , 165.83 , 165.83 ,
       165.83 , 165.83 , 165.83 , 165.83 , 169.435, 169.435, 169.435,
       169.435, 169.435, 169.435, 169.435, 169.435, 169.435, 173.04 ,
       173.04 , 173.04 , 173.04 , 173.04 , 173.04 , 173.04 , 173.04 ,
       176.645, 176.645, 176.645, 176.645, 176.645, 176.645, 176.645,
       180.25 , 180.25 , 180.25 , 180.25 , 180.25 , 180.25 , 183.855,
       183.855, 183.855, 183.855, 187.46 , 187.46 , 191.065, 191.065,
       194.67 , 198.

In [ ]:
H1_media = np.mean(dados_novos)
H1_media

164.0275

In [ ]:
H1_desvio_padrao = np.std(dados_novos)
H1_desvio_padrao

14.0595

In [ ]:
H1_n = len(dados_novos)
H1_n

100

In [ ]:
alpha = 0.05

## Teste Z e Teste T

$$Z = \frac{\bar{x} - 𝜇}{\frac{σ}{\sqrt{n}}}$$

In [ ]:
from statsmodels.stats.weightstats import ztest

In [ ]:
_, p = ztest(dados_originais, dados_novos,
             value = H1_media - H0_media,
             alternative='larger')

In [ ]:
p

0.9999993877283934

In [ ]:
from scipy.stats import ttest_rel

In [ ]:
_, p = ttest_rel(dados_originais, dados_novos)
p

1.3167021402739274e-107

In [ ]:
alpha = 0.01
if p <= alpha:
  print('Hipótese nula rejeitada')
else:
  print('Hipótese alternativa rejeitada')

Hipótese nula rejeitada


### Exercício

In [ ]:
dados = np.array([149. , 160., 147., 189., 175., 168., 156., 160., 152.])
dados

array([149., 160., 147., 189., 175., 168., 156., 160., 152.])

In [ ]:
dados_novos = np.array(dados) * 1.03
dados_novos

array([153.47, 164.8 , 151.41, 194.67, 180.25, 173.04, 160.68, 164.8 ,
       156.56])

In [ ]:
from scipy.stats import ttest_rel

In [ ]:
_, p = ttest_rel(dados, dados_novos)
p

4.072922493930081e-10

In [ ]:
alpha = 0.01
if p <= alpha:
  print('Hipótese nula rejeitada')
else:
  print('Hipótese alternativa rejeitada')

Hipótese nula rejeitada


In [ ]:
## Temos 99% de probabilidade de dizer que as alturas são diferentes. Portanto, rejeitamos a H0
## e aceitamos a Hipótese Alternativa (H1)

# Teste X²

In [ ]:
from scipy.stats import chi2_contingency

In [ ]:
#tabela = np.array([[30, 20], [22, 28]])
tabela = np.array([[45, 5], [5, 45]])

In [ ]:
tabela

array([[45,  5],
       [ 5, 45]])

In [ ]:
tabela.shape

(2, 2)

In [ ]:
_, p, _, _ = chi2_contingency(tabela)
p

6.190717543917382e-15

In [ ]:
alpha = 0.05
if p <= alpha:
  print('Hipótese nula rejeitada')
else:
  print('Hipótese alternativa rejeitada')

Hipótese nula rejeitada


# Seleção de Atributo com testes de Hipóteses - univariate SelectFdr
## Utilizado para feature selection por meio de testes de hipóteses

Testes estatísticos univariados são aqueles que envolvem uma variável dependente, por exemplo, teste t ou teste z para comparação de médias

Documentação: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFpr.html#sklearn.feature_selection.SelectFpr

False discovery rate: https://en.wikipedia.org/wiki/False_discovery_rate

Proporção esperada de erros do tipo I. Um erro do tipo I é quando a hipótese nula é rejeitada incorretamente, ou seja, é obtido um falso positivo

Erro I: https://www.statisticshowto.datasciencecentral.com/probability-and-statistics/statistics-definitions/type-i-error-type-ii-error-decision/

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectFdr
from sklearn.feature_selection import chi2
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [2]:
dataset = pd.read_csv('ad.data', header=None)
dataset.head()

0     1       2     3     4     5     6     7     8     9     ...  1549  \
0   125   125  1.0000     1     0     0     0     0     0     0  ...     0   
1    57   468  8.2105     1     0     0     0     0     0     0  ...     0   
2    33   230  6.9696     1     0     0     0     0     0     0  ...     0   
3    60   468  7.8000     1     0     0     0     0     0     0  ...     0   
4    60   468  7.8000     1     0     0     0     0     0     0  ...     0   

   1550  1551  1552  1553  1554  1555  1556  1557  1558  
0     0     0     0     0     0     0     0     0   ad.  
1     0     0     0     0     0     0     0     0   ad.  
2     0     0     0     0     0     0     0     0   ad.  
3     0     0     0     0     0     0     0     0   ad.  
4     0     0     0     0     0     0     0     0   ad.  

[5 rows x 1559 columns]

In [3]:
dataset.shape

(3279, 1559)

In [4]:
X = dataset.iloc[:, 0:1558].values
X

array([[125.    , 125.    ,   1.    , ...,   0.    ,   0.    ,   0.    ],
       [ 57.    , 468.    ,   8.2105, ...,   0.    ,   0.    ,   0.    ],
       [ 33.    , 230.    ,   6.9696, ...,   0.    ,   0.    ,   0.    ],
       ...,
       [ 23.    , 120.    ,   5.2173, ...,   0.    ,   0.    ,   0.    ],
       [  0.    ,   0.    ,   0.    , ...,   0.    ,   0.    ,   0.    ],
       [ 40.    ,  40.    ,   1.    , ...,   0.    ,   0.    ,   0.    ]])

In [5]:
y = dataset.iloc[:, 1558].values
y

array(['ad.', 'ad.', 'ad.', ..., 'nonad.', 'nonad.', 'nonad.'],
      dtype=object)

In [6]:
np.unique(y, return_counts=True)

(array(['ad.', 'nonad.'], dtype=object), array([ 459, 2820]))

In [7]:
naive1 = GaussianNB()
naive1.fit(X, y)
previsoes1 = naive1.predict(X)
accuracy_score(y, previsoes1)

0.7813357731015553

In [9]:
selecao = SelectFdr(chi2, alpha=0.05)
X_novo = selecao.fit_transform(X, y)

In [10]:
X.shape, X_novo.shape

((3279, 1558), (3279, 490))

In [11]:
selecao.pvalues_

array([2.14710304e-268, 0.00000000e+000, 8.98165813e-150, ...,
       6.03353380e-041, 5.63437216e-012, 9.37945775e-002])

In [12]:
len(selecao.pvalues_)

1558

In [13]:
# selecionando as colunas (true)
colunas = selecao.get_support()
colunas

array([ True,  True,  True, ...,  True,  True, False])

In [14]:
indices = np.where(colunas == True)
indices

(array([   0,    1,    2,    5,    9,   11,   14,   20,   21,   26,   31,
          32,   34,   36,   49,   56,   58,   59,   64,   65,   69,   70,
          86,   91,   95,   96,  102,  104,  105,  106,  113,  133,  134,
         139,  155,  158,  163,  167,  172,  175,  180,  181,  183,  185,
         186,  189,  190,  192,  193,  212,  224,  234,  235,  241,  242,
         244,  246,  248,  249,  251,  259,  264,  265,  266,  267,  268,
         269,  270,  274,  276,  278,  287,  290,  293,  298,  304,  307,
         310,  312,  317,  319,  321,  329,  330,  336,  340,  341,  345,
         346,  347,  350,  351,  355,  356,  357,  359,  361,  366,  367,
         369,  370,  371,  372,  377,  381,  386,  388,  389,  398,  405,
         406,  418,  420,  426,  427,  429,  430,  432,  434,  435,  440,
         441,  451,  455,  457,  460,  465,  470,  472,  477,  478,  482,
         486,  508,  511,  518,  521,  528,  530,  532,  533,  540,  542,
         548,  551,  554,  556,  572, 

In [15]:
naive2 = GaussianNB()
naive2.fit(X_novo, y)
previsoes2 = naive2.predict(X_novo)
accuracy_score(y, previsoes2)

0.9701128392802684